### ISSUE TITLE
which VAE model did you use？

### ISSUE THREAD

**Issue by SophieZhou** [esdolo/FreeVS#4]
The work is very nice and very sensible. But in the paper, you did not tell, which VAE model did you use. Does VAE effect the results? Is any VAE model all right?

**Comment by SophieZhou** [comment]
And by the way, how to generate the text messages or text annotations for each image?

**Comment by SophieZhou** [comment]
> And by the way, how to generate the text messages or text annotations for each image?

In your paper, I have not noticed this information. How to describe the images, using "cars, color, street" all these information?

**Comment by SophieZhou** [comment]
> And by the way, how to generate the text messages or text annotations for each image?
I see, using images to generate text information by CLIP. Is it right.

**Comment by Wastoon** [comment]
Hello bro, have you reproduced this paper successfully? I wonder how to maintain the context consistency when we generate video? Do you have any suggestions?

**Comment by esdolo** [comment]
> The work is very nice and very sensible. But in the paper, you did not tell, which VAE model did you use. Does VAE effect the results? Is any VAE model all right?

We load the VAE model from https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt and did not fine-tune it. May be a fine-tuned VAE mode will do better. 

> And by the way, how to generate the text messages or text annotations for each image?

We use a CLIP vision model to encode the reference image (image -> embedding), no actual test annotations are involved. You can find the CLIP vision model in the above link (/image_encoder).

**Comment by esdolo** [comment]
> Hello bro, have you reproduced this paper successfully? I wonder how to maintain the context consistency when we generate video? Do you have any suggestions?

Our method has a strong temporal consistency on image contents with sufficient LiDAR observations, as the generated videos are very tightly conditioned on LiDAR observations, which are naturally temporal consistent. Maintaining the consistency of image content without sufficient priors is indeed challenging, while generating temporal consistent video is still the key challenge of current video generation models. For SVD models, increasing the number of video frames in each batch and propagating image latents across frames can help.

**Comment by SophieZhou** [comment]
> > The work is very nice and very sensible. But in the paper, you did not tell, which VAE model did you use. Does VAE effect the results? Is any VAE model all right?
> 
> We load the VAE model from https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt and did not fine-tune it. May be a fine-tuned VAE mode will do better.
> 
> > And by the way, how to generate the text messages or text annotations for each image?
> 
> We use a CLIP vision model to encode the reference image (image -> embedding), no actual test annotations are involved. You can find the CLIP vision model in the above link (/image_encoder).

Excellent.

**Comment by SophieZhou** [comment]
> Hello bro, have you reproduced this paper successfully? I wonder how to maintain the context consistency when we generate video? Do you have any suggestions?

Not yet.

**Comment by esdolo** [comment]
> > > Hello bro, have you reproduced this paper successfully? I wonder how to maintain the context consistency when we generate video? Do you have any suggestions?
> > 
> > 
> > Our method has a strong temporal consistency on image contents with sufficient LiDAR observations, as the generated videos are very tightly conditioned on LiDAR observations, which are naturally temporal consistent. Maintaining the consistency of image content without sufficient priors is indeed challenging, while generating temporal consistent video is still the key challenge of current video generation models. For SVD models, increasing the number of video frames in each batch and propagating image latents across frames can help.
> 
> Thanks for your gentelly reply. I also have another question and hope you can help me. When we accumulate several lidar frames (for example, 5 frames) and project the point cloud onto the current frame, how can we avoid occlusion confusion caused by observation view discrepancy decently, especially in some trajectories with curvature? Is the issue of point cloud penetration a significant (essential) problem when using lidar point clouds as control conditions to generate videos from new perspectives?

A trick can solve this problem. You can project LiDAR points of scene contents by step while upholding an occupancy mask in 2D. Specifically, you can project points of objects from near to far and finally points of scene background. In each step, mark the 2D coordinate of projected points as well as its neighbour points as occupied.  Prevent projecting points to 2D positions marked as occupied in previous steps to prevent occlusion confusion between objects.   This described trick is quite complex to implement, we will open-source it along with the project codes.

This trick can not fix the situation when objects are occluded by background objects (like trees). However, such situation is not common when we only accumulate points across a few frames.

**Comment by Wastoon** [comment]
> > > > Hello bro, have you reproduced this paper successfully? I wonder how to maintain the context consistency when we generate video? Do you have any suggestions?
> > > 
> > > 
> > > Our method has a strong temporal consistency on image contents with sufficient LiDAR observations, as the generated videos are very tightly conditioned on LiDAR observations, which are naturally temporal consistent. Maintaining the consistency of image content without sufficient priors is indeed challenging, while generating temporal consistent video is still the key challenge of current video generation models. For SVD models, increasing the number of video frames in each batch and propagating image latents across frames can help.
> > 
> > 
> > Thanks for your gentelly reply. I also have another question and hope you can help me. When we accumulate several lidar frames (for example, 5 frames) and project the point cloud onto the current frame, how can we avoid occlusion confusion caused by observation view discrepancy decently, especially in some trajectories with curvature? Is the issue of point cloud penetration a significant (essential) problem when using lidar point clouds as control conditions to generate videos from new perspectives?
> 
> A trick can solve this problem. You can project LiDAR points of scene contents by step while upholding an occupancy mask in 2D. Specifically, you can project points of objects from near to far and finally points of scene background. In each step, mark the 2D coordinate of projected points as well as its neighbour points as occupied. Prevent projecting points to 2D positions marked as occupied in previous steps to prevent occlusion confusion between objects. This described trick is quite complex to implement, we will open-source it along with the project codes.
> 
> This trick can not fix the situation when objects are occluded by background objects (like trees). However, such situation is not common when we only accumulate points across a few frames.

Got it ! Thanks for your reply! Looking forward to the open source of the nice project!
