### ISSUE TITLE
Pseudo-images question

### ISSUE THREAD

**Issue by SophieZhou** [esdolo/FreeVS#5]
The channel of Pseudo-images is 3?
I am not sure about the Pseudo-images, how to merge lidar points?  Using 5(1,+-2) frames' lidar point cloud as the lidar data of this frame, is it right? 
Especailly, how to color the lidar points?  In each lidar frame, get the colored lidar point in (x,y,z,r,g,b) in last two frames and next two frames, then just use all the data along 5 frames, then project the data with format (x,y,z,r,g,b) to the current frame camera image.  Is it right?

**Comment by esdolo** [comment]
1. right
2. we first extract the color of lidar points in each frame and then accumulate points across frames. For example to generate a pseudo-image in frame T, we project the lidar points in frame T-2 into images in frame T-2 to extract lidar points with colors. We do this in frames T+-2, T+-1, and T, then accumulate all colored lidar points across these frames.

**Comment by SophieZhou** [comment]
Thanks very much.
