### ISSUE TITLE
about ConVNext-T(Liu et al., 2022) encoder 

### ISSUE THREAD

**Issue by SophieZhou** [esdolo/FreeVS#8]
Hi, in your paper, you encode pseudo-images using ConVNext-T(Liu et al., 2022) encoder. But as we know, the model is for classifier with 1k or 22k as head. 
Should I transfer the dims before classification head to cooperate with vae.encode?

**Comment by SophieZhou** [comment]
What size is the output of ConVNext-T(Liu et al., 2022) encoder?

**Comment by esdolo** [comment]
1K or 22K is the number of classes for classification on ImageNet.  You should drop the classification layer of  ConVNext-T and add a final **conv** layer after the conv blocks to downscale the 2D feature channels to vae.encode dimension (=4).

**Comment by SophieZhou** [comment]
> > 1K or 22K is the number of classes for classification on ImageNet. You should drop the classification layer of ConVNext-T and add a final **conv** layer after the conv blocks to downscale the 2D feature channels to vae.encode dimension (=4).
> 
> Yea, add a deconv layer to the last layer before head? As the feature map needed is larger than the final layer output of ConVNext-T.

Is it right? As we know, the dims of last layer feature map before head is 7x7 in the net, it is less than 32x32 if the input is 256x256.

**Comment by esdolo** [comment]
> > > 1K or 22K is the number of classes for classification on ImageNet. You should drop the classification layer of ConVNext-T and add a final **conv** layer after the conv blocks to downscale the 2D feature channels to vae.encode dimension (=4).
> > 
> > 
> > Yea, add a deconv layer to the last layer before head? As the feature map needed is larger than the final layer output of ConVNext-T.
> 
> Is it right? As we know, the dims of last layer feature map before head is 7x7 in the net, it is less than 32x32 if the input is 256x256.


We modified the ConVNext blocks to prevent downsamples in several blocks (the latter ones) so that we can get a 32*32 feature map,

**Comment by SophieZhou** [comment]
> > > > 1K or 22K is the number of classes for classification on ImageNet. You should drop the classification layer of ConVNext-T and add a final **conv** layer after the conv blocks to downscale the 2D feature channels to vae.encode dimension (=4).
> > > 
> > > 
> > > Yea, add a deconv layer to the last layer before head? As the feature map needed is larger than the final layer output of ConVNext-T.
> > 
> > 
> > Is it right? As we know, the dims of last layer feature map before head is 7x7 in the net, it is less than 32x32 if the input is 256x256.
> 
> We modified the ConVNext blocks to prevent downsamples in several blocks (the latter ones) so that we can get a 32*32 feature map,
Got. Thanks very much.

**Comment by zf-666** [comment]
So the input to the network is a T*12*H//8*W//8 feature map
