### ISSUE TITLE
viewpoint transformation simulation problems

### ISSUE THREAD

**Issue by SophieZhou** [esdolo/FreeVS#9]
Hi, in the viewpoint transformation simulation part.
I am not sure what the mean is. In my opinion,  within 8 frames, you can use the correct 8 pseudo-images frames in accordance with rgb frames from the same cameras. 
After viewpoint transformation simulation transforms, the mismatched data is from the same camera(with different frameid) or nearby camera(with the same frameid)?

**Comment by esdolo** [comment]
> Hi, in the viewpoint transformation simulation part. I am not sure what the mean is. In my opinion, within 8 frames, you can use the correct 8 pseudo-images frames in accordance with rgb frames from the same cameras. After viewpoint transformation simulation transforms, the mismatched data is from the same camera(with different frameid) or nearby camera(with the same frameid)?

The same camera with different frame id. For example, when we use observation of the side-right camera in past frames to generate side-right views in future frames if the vehicle is moving forward, we are stimulating cases when the camera moves to its left.

**Comment by SophieZhou** [comment]
The idea is very smart. Thanks.
